import asyncio
import sys
sys.path.append(".")
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy import Column, String, Text, Integer, Boolean, DateTime, ARRAY
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
import uuid
from app.config import settings

engine = create_async_engine(settings.DATABASE_URL, echo=False)
AsyncSession = async_sessionmaker(engine, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

class ErrorCard(Base):
    __tablename__ = "error_cards"
    id              = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    code            = Column(String(100), index=True)
    title           = Column(String(500), nullable=False)
    description     = Column(Text)
    category        = Column(String(50), nullable=False)
    subcategory     = Column(String(100))
    severity        = Column(String(10), nullable=False)
    causes          = Column(JSONB)
    impact          = Column(Text)
    procedure_quick = Column(JSONB)
    procedure_full  = Column(JSONB)
    commands        = Column(JSONB)
    prevention      = Column(Text)
    tags            = Column(ARRAY(String))
    aliases         = Column(ARRAY(String))
    lang_data       = Column(JSONB)
    view_count      = Column(Integer, default=0)
    resolve_count   = Column(Integer, default=0)
    is_verified     = Column(Boolean, default=True)
    created_at      = Column(DateTime(timezone=True), server_default=func.now())
    updated_at      = Column(DateTime(timezone=True), onupdate=func.now())

ERRORS = [
  {"code":"0x0000007E","title":"SYSTEM_THREAD_EXCEPTION_NOT_HANDLED","category":"windows","severity":"critical","description":"Exception non geree par un thread systeme, souvent causee par un pilote incompatible.","causes":[{"description":"Pilote incompatible ou corrompu","probability":0.6},{"description":"Fichiers systeme corrompus","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Demarrer en mode sans echec"},{"step":2,"instruction":"Desinstaller les pilotes recemment installes"},{"step":3,"instruction":"Executer sfc /scannow dans cmd en admin"}],"commands":[{"os":"windows","command":"sfc /scannow","desc":"Verification fichiers systeme"},{"os":"windows","command":"dism /online /cleanup-image /restorehealth","desc":"Reparation image Windows"}],"tags":["bsod","windows","pilote"],"prevention":"Maintenir les pilotes a jour et creer des points de restauration reguliers."},
  {"code":"0x0000000A","title":"IRQL_NOT_LESS_OR_EQUAL","category":"windows","severity":"critical","description":"Acces memoire a un niveau IRQL incorrect, generalement lie a un pilote defectueux.","causes":[{"description":"Pilote reseau ou GPU defectueux","probability":0.7},{"description":"RAM defectueuse","probability":0.2}],"procedure_quick":[{"step":1,"instruction":"Demarrer en mode sans echec"},{"step":2,"instruction":"Desinstaller le dernier pilote installe"},{"step":3,"instruction":"Tester la RAM avec Windows Memory Diagnostic"}],"commands":[{"os":"windows","command":"verifier /standard /all","desc":"Verificateur de pilotes"},{"os":"windows","command":"mdsched.exe","desc":"Diagnostic memoire Windows"}],"tags":["bsod","windows","memoire","pilote"],"prevention":"Eviter l overclocking et maintenir les pilotes a jour."},
  {"code":"0x00000050","title":"PAGE_FAULT_IN_NONPAGED_AREA","category":"windows","severity":"critical","description":"Acces a une zone memoire non paginee invalide.","causes":[{"description":"RAM defectueuse","probability":0.5},{"description":"Pilote corrompu","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Executer le diagnostic memoire Windows"},{"step":2,"instruction":"Verifier les pilotes avec le verificateur"},{"step":3,"instruction":"Restaurer le systeme a un point anterieur"}],"commands":[{"os":"windows","command":"mdsched.exe","desc":"Diagnostic memoire"},{"os":"windows","command":"sfc /scannow","desc":"Verification systeme"}],"tags":["bsod","memoire","windows"],"prevention":"Tester regulierement la RAM et maintenir le systeme a jour."},
  {"code":"0x0000003B","title":"SYSTEM_SERVICE_EXCEPTION","category":"windows","severity":"critical","description":"Exception dans un service systeme Windows.","causes":[{"description":"Pilote graphique defectueux","probability":0.6},{"description":"Logiciel antivirus conflictuel","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Mettre a jour les pilotes graphiques"},{"step":2,"instruction":"Desactiver temporairement l antivirus"},{"step":3,"instruction":"Executer DISM pour reparer Windows"}],"commands":[{"os":"windows","command":"dism /online /cleanup-image /restorehealth","desc":"Reparation Windows"},{"os":"windows","command":"sfc /scannow","desc":"Verification fichiers"}],"tags":["bsod","windows","gpu"],"prevention":"Maintenir GPU et Windows a jour."},
  {"code":"0x000000EF","title":"CRITICAL_PROCESS_DIED","category":"windows","severity":"critical","description":"Un processus critique Windows s est arrete de facon inattendue.","causes":[{"description":"Fichiers systeme corrompus","probability":0.5},{"description":"Infection malware","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Executer sfc /scannow"},{"step":2,"instruction":"Lancer un scan antivirus complet"},{"step":3,"instruction":"Reparer Windows avec DISM"}],"commands":[{"os":"windows","command":"sfc /scannow","desc":"Reparation systeme"},{"os":"windows","command":"dism /online /cleanup-image /restorehealth","desc":"DISM repair"}],"tags":["bsod","windows","critique"],"prevention":"Scanner regulierement le systeme et maintenir Windows a jour."},
  {"code":"0x80070005","title":"Access Denied","category":"windows","severity":"high","description":"Acces refuse - permissions insuffisantes pour effectuer l operation.","causes":[{"description":"Droits administrateur manquants","probability":0.6},{"description":"Permissions NTFS incorrectes","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Clic droit sur le programme > Executer en tant qu administrateur"},{"step":2,"instruction":"Verifier les permissions du dossier concerne"},{"step":3,"instruction":"Desactiver temporairement l UAC si necessaire"}],"commands":[{"os":"windows","command":"icacls C:\\dossier /grant Administrateurs:F","desc":"Accorder permissions completes"},{"os":"windows","command":"takeown /f C:\\fichier","desc":"Prendre possession du fichier"}],"tags":["windows","permissions","acces"],"prevention":"Gerer correctement les permissions NTFS et les comptes utilisateurs."},
  {"code":"0x80070002","title":"Le fichier specifie est introuvable","category":"windows","severity":"medium","description":"Windows ne trouve pas le fichier ou chemin specifie.","causes":[{"description":"Fichier supprime ou deplac","probability":0.5},{"description":"Chemin incorrect","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Verifier que le fichier existe bien"},{"step":2,"instruction":"Rechercher le fichier avec Windows Search"},{"step":3,"instruction":"Reinstaller le programme concerne"}],"commands":[{"os":"windows","command":"where nomfichier.exe","desc":"Chercher executable"},{"os":"windows","command":"dir /s nomfichier","desc":"Chercher fichier recursif"}],"tags":["windows","fichier","introuvable"],"prevention":"Sauvegarder les fichiers importants et eviter de deplacer les fichiers systeme."},
  {"code":"ENOENT","title":"No such file or directory","category":"linux","severity":"medium","description":"Le fichier ou repertoire specifie n existe pas.","causes":[{"description":"Chemin incorrect","probability":0.5},{"description":"Fichier supprime","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Verifier le chemin avec ls -la"},{"step":2,"instruction":"Creer le fichier/dossier manquant"},{"step":3,"instruction":"Verifier les permissions"}],"commands":[{"os":"linux","command":"ls -la /chemin/","desc":"Lister les fichiers"},{"os":"linux","command":"find / -name nomfichier 2>/dev/null","desc":"Chercher le fichier"}],"tags":["linux","fichier","erreur"],"prevention":"Toujours verifier l existence des chemins avant de les utiliser."},
  {"code":"EACCES","title":"Permission denied","category":"linux","severity":"medium","description":"Permissions insuffisantes pour acceder au fichier ou repertoire.","causes":[{"description":"Droits utilisateur insuffisants","probability":0.7},{"description":"Fichier appartenant a root","probability":0.2}],"procedure_quick":[{"step":1,"instruction":"Verifier les permissions avec ls -la"},{"step":2,"instruction":"Utiliser sudo si necessaire"},{"step":3,"instruction":"Modifier les permissions avec chmod"}],"commands":[{"os":"linux","command":"ls -la fichier","desc":"Voir les permissions"},{"os":"linux","command":"chmod 755 fichier","desc":"Modifier permissions"},{"os":"linux","command":"sudo chown user:user fichier","desc":"Changer proprietaire"}],"tags":["linux","permissions","acces"],"prevention":"Gerer correctement les permissions Unix et eviter d utiliser root inutilement."},
  {"code":"SIGKILL","title":"Process Killed","category":"linux","severity":"high","description":"Le processus a ete tue par le signal SIGKILL, souvent par l OOM killer.","causes":[{"description":"Manque de memoire RAM","probability":0.7},{"description":"Processus tue manuellement","probability":0.2}],"procedure_quick":[{"step":1,"instruction":"Verifier la memoire disponible avec free -h"},{"step":2,"instruction":"Identifier les processus gourmands avec top"},{"step":3,"instruction":"Augmenter la memoire swap"}],"commands":[{"os":"linux","command":"free -h","desc":"Voir memoire disponible"},{"os":"linux","command":"dmesg | grep -i oom","desc":"Voir logs OOM killer"},{"os":"linux","command":"top","desc":"Monitorer processus"}],"tags":["linux","memoire","processus"],"prevention":"Monitorer la memoire et configurer des limites par processus."},
  {"code":"npm ERR! 404","title":"Package not found","category":"javascript","severity":"medium","description":"Le package npm demande n existe pas dans le registry.","causes":[{"description":"Nom de package incorrect","probability":0.5},{"description":"Package depublie","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Verifier l orthographe du package sur npmjs.com"},{"step":2,"instruction":"Verifier la version demandee"},{"step":3,"instruction":"Chercher une alternative au package"}],"commands":[{"os":"any","command":"npm search nom-package","desc":"Chercher un package"},{"os":"any","command":"npm install package@latest","desc":"Installer derniere version"}],"tags":["npm","javascript","package"],"prevention":"Toujours verifier le nom exact du package sur npmjs.com."},
  {"code":"npm ERR! 401","title":"Unauthorized","category":"javascript","severity":"medium","description":"Authentification requise pour acceder au registry npm.","causes":[{"description":"Non connecte au registry","probability":0.6},{"description":"Token expire","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Se connecter avec npm login"},{"step":2,"instruction":"Verifier la configuration .npmrc"},{"step":3,"instruction":"Regenerer le token d acces"}],"commands":[{"os":"any","command":"npm login","desc":"Se connecter au registry"},{"os":"any","command":"npm whoami","desc":"Verifier l utilisateur connecte"},{"os":"any","command":"npm config get registry","desc":"Voir le registry configure"}],"tags":["npm","auth","javascript"],"prevention":"Maintenir les tokens npm a jour et utiliser des variables d environnement."},
  {"code":"MODULE_NOT_FOUND","title":"Cannot find module","category":"javascript","severity":"medium","description":"Node.js ne trouve pas le module demande.","causes":[{"description":"Module non installe","probability":0.6},{"description":"Chemin d import incorrect","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Executer npm install"},{"step":2,"instruction":"Verifier le chemin d import dans le code"},{"step":3,"instruction":"Supprimer node_modules et reinstaller"}],"commands":[{"os":"any","command":"npm install","desc":"Installer les dependances"},{"os":"any","command":"rm -rf node_modules && npm install","desc":"Reinstallation complete"}],"tags":["nodejs","module","javascript"],"prevention":"Commiter le package-lock.json et utiliser les imports relatifs corrects."},
  {"code":"ORA-00942","title":"Table or view does not exist","category":"sql","severity":"high","description":"La table ou vue referencee n existe pas dans la base de donnees.","causes":[{"description":"Nom de table incorrect","probability":0.5},{"description":"Schema incorrect","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Verifier l orthographe de la table"},{"step":2,"instruction":"Verifier le schema avec SELECT * FROM all_tables"},{"step":3,"instruction":"Verifier les privileges sur la table"}],"commands":[{"os":"oracle","command":"SELECT table_name FROM all_tables WHERE table_name LIKE '%NOM%';","desc":"Chercher la table"},{"os":"oracle","command":"SELECT * FROM user_tables;","desc":"Lister les tables utilisateur"}],"tags":["oracle","sql","table"],"prevention":"Toujours verifier l existence des tables avant de les referencer."},
  {"code":"ORA-01017","title":"Invalid username/password","category":"sql","severity":"high","description":"Identifiants Oracle incorrects.","causes":[{"description":"Mot de passe incorrect","probability":0.6},{"description":"Compte verrouille","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Verifier le nom d utilisateur et mot de passe"},{"step":2,"instruction":"Verifier si le compte est verrouille"},{"step":3,"instruction":"Reinitialiser le mot de passe"}],"commands":[{"os":"oracle","command":"ALTER USER username IDENTIFIED BY newpassword;","desc":"Changer mot de passe"},{"os":"oracle","command":"ALTER USER username ACCOUNT UNLOCK;","desc":"Deverrouiller compte"}],"tags":["oracle","auth","sql"],"prevention":"Utiliser un gestionnaire de secrets et renouveler les mots de passe regulierement."},
  {"code":"SQLSTATE 23000","title":"Integrity Constraint Violation","category":"sql","severity":"medium","description":"Violation d une contrainte d integrite (cle unique, cle etrangere, etc).","causes":[{"description":"Valeur dupliquee sur une cle unique","probability":0.5},{"description":"Reference a une cle etrangere inexistante","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Identifier la contrainte violee dans le message d erreur"},{"step":2,"instruction":"Verifier les donnees existantes"},{"step":3,"instruction":"Corriger les donnees avant insertion"}],"commands":[{"os":"sql","command":"SELECT * FROM information_schema.table_constraints WHERE table_name='ma_table';","desc":"Voir les contraintes"},{"os":"sql","command":"SHOW CREATE TABLE ma_table;","desc":"Voir la structure"}],"tags":["sql","contrainte","integrite"],"prevention":"Valider les donnees cote application avant insertion en base."},
  {"code":"Docker: Cannot connect to daemon","title":"Docker daemon non demarre","category":"docker","severity":"high","description":"Le client Docker ne peut pas se connecter au daemon Docker.","causes":[{"description":"Service Docker non demarre","probability":0.7},{"description":"Permissions insuffisantes","probability":0.2}],"procedure_quick":[{"step":1,"instruction":"Demarrer Docker Desktop"},{"step":2,"instruction":"Verifier que le service Docker tourne"},{"step":3,"instruction":"Redemarrer le service Docker"}],"commands":[{"os":"windows","command":"net start docker","desc":"Demarrer service Docker"},{"os":"linux","command":"sudo systemctl start docker","desc":"Demarrer Docker Linux"},{"os":"linux","command":"sudo usermod -aG docker $USER","desc":"Ajouter utilisateur au groupe docker"}],"tags":["docker","daemon","service"],"prevention":"Configurer Docker pour demarrer automatiquement au lancement du systeme."},
  {"code":"Error: ImagePullBackOff","title":"Kubernetes ImagePullBackOff","category":"docker","severity":"high","description":"Kubernetes ne peut pas telecharger l image Docker specifiee.","causes":[{"description":"Image inexistante ou tag incorrect","probability":0.5},{"description":"Registry prive sans credentials","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Verifier le nom et tag de l image"},{"step":2,"instruction":"Se connecter au registry prive"},{"step":3,"instruction":"Creer un secret Kubernetes pour le registry"}],"commands":[{"os":"any","command":"kubectl describe pod nom-pod","desc":"Voir details du pod"},{"os":"any","command":"kubectl get events","desc":"Voir les evenements"},{"os":"any","command":"docker pull nom-image","desc":"Tester le pull manuel"}],"tags":["kubernetes","docker","image"],"prevention":"Toujours tagger les images avec des versions specifiques, pas latest."},
  {"code":"SyntaxError","title":"Python SyntaxError","category":"python","severity":"medium","description":"Erreur de syntaxe dans le code Python.","causes":[{"description":"Parenthese ou crochet manquant","probability":0.4},{"description":"Indentation incorrecte","probability":0.4}],"procedure_quick":[{"step":1,"instruction":"Lire le message d erreur indiquant la ligne"},{"step":2,"instruction":"Verifier la ligne indiquee et les lignes precedentes"},{"step":3,"instruction":"Utiliser un linter comme pylint ou flake8"}],"commands":[{"os":"any","command":"python -m py_compile script.py","desc":"Verifier la syntaxe"},{"os":"any","command":"pylint script.py","desc":"Analyser le code"}],"tags":["python","syntaxe","code"],"prevention":"Utiliser un editeur avec coloration syntaxique et linting automatique."},
  {"code":"ImportError","title":"Python ImportError","category":"python","severity":"medium","description":"Impossible d importer le module specifie.","causes":[{"description":"Module non installe","probability":0.6},{"description":"Nom de module incorrect","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Installer le module avec pip install nom-module"},{"step":2,"instruction":"Verifier l environnement virtuel actif"},{"step":3,"instruction":"Verifier l orthographe du module"}],"commands":[{"os":"any","command":"pip install nom-module","desc":"Installer le module"},{"os":"any","command":"pip list","desc":"Lister les modules installes"},{"os":"any","command":"pip show nom-module","desc":"Infos sur le module"}],"tags":["python","import","module"],"prevention":"Utiliser des environnements virtuels et maintenir requirements.txt a jour."},
  {"code":"ConnectionRefusedError","title":"Python Connection Refused","category":"python","severity":"high","description":"La connexion au serveur ou service cible a ete refusee.","causes":[{"description":"Service cible non demarre","probability":0.6},{"description":"Port ou host incorrect","probability":0.3}],"procedure_quick":[{"step":1,"instruction":"Verifier que le service cible est demarre"},{"step":2,"instruction":"Verifier le port et l adresse IP"},{"step":3,"instruction":"Verifier le pare-feu"}],"commands":[{"os":"windows","command":"netstat -ano | findstr :PORT","desc":"Verifier si le port est ouvert"},{"os":"linux","command":"ss -tulpn | grep :PORT","desc":"Verifier le port Linux"}],"tags":["python","reseau","connexion"],"prevention":"Implementer des mecanismes de retry et de timeout dans le code."}
]

async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    
    async with AsyncSession() as session:
        count = 0
        for e in ERRORS:
            card = ErrorCard(
                id=uuid.uuid4(),
                code=e["code"],
                title=e["title"],
                category=e["category"],
                severity=e["severity"],
                description=e.get("description",""),
                causes=e.get("causes",[]),
                procedure_quick=e.get("procedure_quick",[]),
                commands=e.get("commands",[]),
                tags=e.get("tags",[]),
                prevention=e.get("prevention",""),
                is_verified=True
            )
            session.add(card)
            count += 1
        await session.commit()
        print(f"Seed termine : {count} erreurs inserees dans PostgreSQL !")

if __name__ == "__main__":
    asyncio.run(seed())